[project-python]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fuzz>=0.1.1",
    "openpy>=0.0.2",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "thefuzz>=0.22.1",
    "xlrd>=2.0.2",
]
